version: 0.2

phases:
  install:
    commands:
#      Create CloudFormation Template
      - aws cloudformation package --template-file samTemplate.yml --kms-key-id ${KMSKEYID} --s3-bucket ${BUCKET} --output-template-file outputSamTemplate.yaml
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${IGDBCOMECR}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands: 
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker run --name image_test --rm -i -t . bash
      - docker exec -d image_test ./run.sh
  post_build:
    commands: 
      - echo Build complete on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml