AWSTemplateFormatVersion: '2010-09-09'
Description: Create ECS Service with Fargate

Resources:
# ---- Docker Container settings ----
  IGDBcomCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: igdbcom-cluster
  
  IGDBcomTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
          - "FARGATE"
      Cpu: "1024"
      Memory: "2048"
      NetworkMode: "awsvpc"
      ExecutionRoleArn: !GetAtt IGDBcomExecutionRole.Arn
      TaskRoleArn: !GetAtt IGDBcomExecutionRole.Arn
      Family: "igdbcom"
      ContainerDefinitions:
        - 
          Name: "igdbcom-container"
          Image: 121715975140.dkr.ecr.us-east-1.amazonaws.com/igdbcom-image
          PortMappings: 
            - 
              ContainerPort: 4000
              HostPort: 4000
              Protocol: tcp

  IGDBcomService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref IGDBcomCluster
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref IGDBcomSecurityGroup
          Subnets: 
            - !Ref Subnet1
      ServiceName: "igdbcom-service"
      LoadBalancers:
        - 
          ContainerName: "igdbcom-container"
          ContainerPort: 4000
          TargetGroupArn: !Ref IGDBELBTargetGroup
      TaskDefinition: !Ref IGDBcomTaskDefinition

# ---- AWS Autoscaling ----

  IGDBcomScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Join ['/', [service, !Ref IGDBcomCluster, !GetAtt IGDBcomService.Name]]
      RoleArn: !GetAtt IGDBcomAutoscalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  IGDBcomTargetTrackingScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: igdbcom-autoscaling-policy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref IGDBcomScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:  
          PredifinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        TargetValue: 95

# ---- AWS Internet Access settings ----

  IGDBLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: igdbcom-loadbalancer
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref IGDBcomSecurityGroup
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      Type: application

  IGDBELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - IGDBLoadBalancer
    Properties:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'igdb']]
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref 'IGDBcomVPC'
      TargetType: 'ip'

  IGDBcomLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - IGDBLoadBalancer
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref IGDBELBTargetGroup
          Type: 'forward'
      LoadBalancerArn: !Ref IGDBLoadBalancer
      Port: 80
      Protocol: HTTP

  IGDBcomVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - 
          Key: "Name"
          Value: "IGDBcom"
  
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref IGDBcomVPC
      CidrBlock: 10.0.6.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: "Name"
          Value: "IGDBcom"
  
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1f
      VpcId: !Ref IGDBcomVPC
      CidrBlock: 10.0.24.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: "Name"
          Value: "IGDBcom"
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
          - 
            Key: "Name"
            Value: "IGDBcom"
  
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref IGDBcomVPC
  
  IGDBcomSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for IGDBcom"
      GroupName: "igdbcom-security"
      SecurityGroupIngress: 
        - 
          IpProtocol: tcp
          FromPort: 4000
          ToPort: 4000
          CidrIp: 0.0.0.0/0
        - 
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - 
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
        - 
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      VpcId: !Ref IGDBcomVPC
      Tags:
        - 
          Key: "Name"
          Value: "IGDBcom"

  IGDBcomRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref IGDBcomVPC
      Tags:
        - 
          Key: "Name"
          Value: "IGDBcom"

  IGDBcomRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref IGDBcomRouteTable

  IGDBRouteSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref IGDBcomRouteTable
      SubnetId: !Ref Subnet1

  IGDBRouteSubnetAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref IGDBcomRouteTable
      SubnetId: !Ref Subnet2

# ---- ECS execution role ----

  IGDBcomExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "igdbcom-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - 
          PolicyName: "igdbcom-execution-policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"

  IGDBcomAutoscalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IGDBcom-autoscaler-policy
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        -  
          PolicyName: service-autoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - ecs:DescribeService
                  - ecs:UpdateService
                  - cloudwatch:DescribeAlarms
                  - cloudwwatch:PutMetricAlarm
                Resource: '*'
    